# Generated by Django 2.1.2 on 2018-11-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Preparing', max_length=20)),
                ('progress', models.FloatField(blank=True, default=None, null=True)),
                ('remain', models.IntegerField(blank=True, default=None, null=True)),
                ('destroy', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
